// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base.proto

#include "base.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace ylg {
namespace internal {

inline constexpr PluginBase::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _version_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _loglevel_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _installedlocation_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _installedtimestamp_{::uint64_t{0u}},
        _startedtimestamp_{::uint64_t{0u}},
        _runningduration_{::uint64_t{0u}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR PluginBase::PluginBase(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct PluginBaseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PluginBaseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PluginBaseDefaultTypeInternal() {}
  union {
    PluginBase _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PluginBaseDefaultTypeInternal _PluginBase_default_instance_;
}  // namespace internal
}  // namespace ylg
static ::_pb::Metadata file_level_metadata_base_2eproto[1];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_base_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_base_2eproto = nullptr;
const ::uint32_t TableStruct_base_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::ylg::internal::PluginBase, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::ylg::internal::PluginBase, _impl_._name_),
    PROTOBUF_FIELD_OFFSET(::ylg::internal::PluginBase, _impl_._version_),
    PROTOBUF_FIELD_OFFSET(::ylg::internal::PluginBase, _impl_._loglevel_),
    PROTOBUF_FIELD_OFFSET(::ylg::internal::PluginBase, _impl_._installedlocation_),
    PROTOBUF_FIELD_OFFSET(::ylg::internal::PluginBase, _impl_._installedtimestamp_),
    PROTOBUF_FIELD_OFFSET(::ylg::internal::PluginBase, _impl_._startedtimestamp_),
    PROTOBUF_FIELD_OFFSET(::ylg::internal::PluginBase, _impl_._runningduration_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::ylg::internal::PluginBase)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::ylg::internal::_PluginBase_default_instance_._instance,
};
const char descriptor_table_protodef_base_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\nbase.proto\022\014ylg.internal\"\256\001\n\nPluginBas"
    "e\022\r\n\005_name\030\001 \001(\t\022\020\n\010_version\030\002 \001(\t\022\021\n\t_l"
    "ogLevel\030\003 \001(\t\022\032\n\022_installedLocation\030\004 \001("
    "\t\022\033\n\023_installedTimestamp\030\005 \001(\004\022\031\n\021_start"
    "edTimestamp\030\006 \001(\004\022\030\n\020_runningDuration\030\007 "
    "\001(\004*$\n\nAgentState\022\n\n\006Offine\020\000\022\n\n\006Online\020"
    "\001b\006proto3"
};
static ::absl::once_flag descriptor_table_base_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_base_2eproto = {
    false,
    false,
    249,
    descriptor_table_protodef_base_2eproto,
    "base.proto",
    &descriptor_table_base_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_base_2eproto::offsets,
    file_level_metadata_base_2eproto,
    file_level_enum_descriptors_base_2eproto,
    file_level_service_descriptors_base_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_base_2eproto_getter() {
  return &descriptor_table_base_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_base_2eproto(&descriptor_table_base_2eproto);
namespace ylg {
namespace internal {
const ::google::protobuf::EnumDescriptor* AgentState_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_base_2eproto);
  return file_level_enum_descriptors_base_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t AgentState_internal_data_[] = {
    131072u, 0u, };
bool AgentState_IsValid(int value) {
  return 0 <= value && value <= 1;
}
// ===================================================================

class PluginBase::_Internal {
 public:
};

PluginBase::PluginBase(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ylg.internal.PluginBase)
}
inline PROTOBUF_NDEBUG_INLINE PluginBase::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _name_(arena, from._name_),
        _version_(arena, from._version_),
        _loglevel_(arena, from._loglevel_),
        _installedlocation_(arena, from._installedlocation_),
        _cached_size_{0} {}

PluginBase::PluginBase(
    ::google::protobuf::Arena* arena,
    const PluginBase& from)
    : ::google::protobuf::Message(arena) {
  PluginBase* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, _installedtimestamp_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, _installedtimestamp_),
           offsetof(Impl_, _runningduration_) -
               offsetof(Impl_, _installedtimestamp_) +
               sizeof(Impl_::_runningduration_));

  // @@protoc_insertion_point(copy_constructor:ylg.internal.PluginBase)
}
inline PROTOBUF_NDEBUG_INLINE PluginBase::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _name_(arena),
        _version_(arena),
        _loglevel_(arena),
        _installedlocation_(arena),
        _cached_size_{0} {}

inline void PluginBase::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, _installedtimestamp_),
           0,
           offsetof(Impl_, _runningduration_) -
               offsetof(Impl_, _installedtimestamp_) +
               sizeof(Impl_::_runningduration_));
}
PluginBase::~PluginBase() {
  // @@protoc_insertion_point(destructor:ylg.internal.PluginBase)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void PluginBase::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_._name_.Destroy();
  _impl_._version_.Destroy();
  _impl_._loglevel_.Destroy();
  _impl_._installedlocation_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void PluginBase::Clear() {
// @@protoc_insertion_point(message_clear_start:ylg.internal.PluginBase)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_._name_.ClearToEmpty();
  _impl_._version_.ClearToEmpty();
  _impl_._loglevel_.ClearToEmpty();
  _impl_._installedlocation_.ClearToEmpty();
  ::memset(&_impl_._installedtimestamp_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_._runningduration_) -
      reinterpret_cast<char*>(&_impl_._installedtimestamp_)) + sizeof(_impl_._runningduration_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* PluginBase::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 7, 0, 72, 2> PluginBase::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    7, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967168,  // skipmap
    offsetof(decltype(_table_), field_entries),
    7,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_PluginBase_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string _name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(PluginBase, _impl_._name_)}},
    // string _version = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(PluginBase, _impl_._version_)}},
    // string _logLevel = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(PluginBase, _impl_._loglevel_)}},
    // string _installedLocation = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(PluginBase, _impl_._installedlocation_)}},
    // uint64 _installedTimestamp = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(PluginBase, _impl_._installedtimestamp_), 63>(),
     {40, 63, 0, PROTOBUF_FIELD_OFFSET(PluginBase, _impl_._installedtimestamp_)}},
    // uint64 _startedTimestamp = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(PluginBase, _impl_._startedtimestamp_), 63>(),
     {48, 63, 0, PROTOBUF_FIELD_OFFSET(PluginBase, _impl_._startedtimestamp_)}},
    // uint64 _runningDuration = 7;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(PluginBase, _impl_._runningduration_), 63>(),
     {56, 63, 0, PROTOBUF_FIELD_OFFSET(PluginBase, _impl_._runningduration_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string _name = 1;
    {PROTOBUF_FIELD_OFFSET(PluginBase, _impl_._name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string _version = 2;
    {PROTOBUF_FIELD_OFFSET(PluginBase, _impl_._version_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string _logLevel = 3;
    {PROTOBUF_FIELD_OFFSET(PluginBase, _impl_._loglevel_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string _installedLocation = 4;
    {PROTOBUF_FIELD_OFFSET(PluginBase, _impl_._installedlocation_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // uint64 _installedTimestamp = 5;
    {PROTOBUF_FIELD_OFFSET(PluginBase, _impl_._installedtimestamp_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // uint64 _startedTimestamp = 6;
    {PROTOBUF_FIELD_OFFSET(PluginBase, _impl_._startedtimestamp_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // uint64 _runningDuration = 7;
    {PROTOBUF_FIELD_OFFSET(PluginBase, _impl_._runningduration_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
  }},
  // no aux_entries
  {{
    "\27\5\10\11\22\0\0\0"
    "ylg.internal.PluginBase"
    "_name"
    "_version"
    "_logLevel"
    "_installedLocation"
  }},
};

::uint8_t* PluginBase::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ylg.internal.PluginBase)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string _name = 1;
  if (!this->_internal__name().empty()) {
    const std::string& _s = this->_internal__name();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ylg.internal.PluginBase._name");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // string _version = 2;
  if (!this->_internal__version().empty()) {
    const std::string& _s = this->_internal__version();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ylg.internal.PluginBase._version");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // string _logLevel = 3;
  if (!this->_internal__loglevel().empty()) {
    const std::string& _s = this->_internal__loglevel();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ylg.internal.PluginBase._logLevel");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  // string _installedLocation = 4;
  if (!this->_internal__installedlocation().empty()) {
    const std::string& _s = this->_internal__installedlocation();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ylg.internal.PluginBase._installedLocation");
    target = stream->WriteStringMaybeAliased(4, _s, target);
  }

  // uint64 _installedTimestamp = 5;
  if (this->_internal__installedtimestamp() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        5, this->_internal__installedtimestamp(), target);
  }

  // uint64 _startedTimestamp = 6;
  if (this->_internal__startedtimestamp() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        6, this->_internal__startedtimestamp(), target);
  }

  // uint64 _runningDuration = 7;
  if (this->_internal__runningduration() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        7, this->_internal__runningduration(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ylg.internal.PluginBase)
  return target;
}

::size_t PluginBase::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ylg.internal.PluginBase)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string _name = 1;
  if (!this->_internal__name().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal__name());
  }

  // string _version = 2;
  if (!this->_internal__version().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal__version());
  }

  // string _logLevel = 3;
  if (!this->_internal__loglevel().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal__loglevel());
  }

  // string _installedLocation = 4;
  if (!this->_internal__installedlocation().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal__installedlocation());
  }

  // uint64 _installedTimestamp = 5;
  if (this->_internal__installedtimestamp() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
        this->_internal__installedtimestamp());
  }

  // uint64 _startedTimestamp = 6;
  if (this->_internal__startedtimestamp() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
        this->_internal__startedtimestamp());
  }

  // uint64 _runningDuration = 7;
  if (this->_internal__runningduration() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
        this->_internal__runningduration());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData PluginBase::_class_data_ = {
    PluginBase::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* PluginBase::GetClassData() const {
  return &_class_data_;
}

void PluginBase::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<PluginBase*>(&to_msg);
  auto& from = static_cast<const PluginBase&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ylg.internal.PluginBase)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal__name().empty()) {
    _this->_internal_set__name(from._internal__name());
  }
  if (!from._internal__version().empty()) {
    _this->_internal_set__version(from._internal__version());
  }
  if (!from._internal__loglevel().empty()) {
    _this->_internal_set__loglevel(from._internal__loglevel());
  }
  if (!from._internal__installedlocation().empty()) {
    _this->_internal_set__installedlocation(from._internal__installedlocation());
  }
  if (from._internal__installedtimestamp() != 0) {
    _this->_internal_set__installedtimestamp(from._internal__installedtimestamp());
  }
  if (from._internal__startedtimestamp() != 0) {
    _this->_internal_set__startedtimestamp(from._internal__startedtimestamp());
  }
  if (from._internal__runningduration() != 0) {
    _this->_internal_set__runningduration(from._internal__runningduration());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PluginBase::CopyFrom(const PluginBase& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ylg.internal.PluginBase)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool PluginBase::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* PluginBase::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void PluginBase::InternalSwap(PluginBase* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_._name_, &other->_impl_._name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_._version_, &other->_impl_._version_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_._loglevel_, &other->_impl_._loglevel_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_._installedlocation_, &other->_impl_._installedlocation_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PluginBase, _impl_._runningduration_)
      + sizeof(PluginBase::_impl_._runningduration_)
      - PROTOBUF_FIELD_OFFSET(PluginBase, _impl_._installedtimestamp_)>(
          reinterpret_cast<char*>(&_impl_._installedtimestamp_),
          reinterpret_cast<char*>(&other->_impl_._installedtimestamp_));
}

::google::protobuf::Metadata PluginBase::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_base_2eproto_getter, &descriptor_table_base_2eproto_once,
      file_level_metadata_base_2eproto[0]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace internal
}  // namespace ylg
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
