// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: controller.proto

#include "controller.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace ylg {
namespace internal {

inline constexpr UnregisterAgentRespond::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _agentid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR UnregisterAgentRespond::UnregisterAgentRespond(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct UnregisterAgentRespondDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UnregisterAgentRespondDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UnregisterAgentRespondDefaultTypeInternal() {}
  union {
    UnregisterAgentRespond _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UnregisterAgentRespondDefaultTypeInternal _UnregisterAgentRespond_default_instance_;

inline constexpr UnregisterAgentRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _agentid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR UnregisterAgentRequest::UnregisterAgentRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct UnregisterAgentRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UnregisterAgentRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UnregisterAgentRequestDefaultTypeInternal() {}
  union {
    UnregisterAgentRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UnregisterAgentRequestDefaultTypeInternal _UnregisterAgentRequest_default_instance_;

inline constexpr ReportAgentState::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _agentid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _state_{static_cast< ::ylg::internal::AgentState >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ReportAgentState::ReportAgentState(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ReportAgentStateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ReportAgentStateDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ReportAgentStateDefaultTypeInternal() {}
  union {
    ReportAgentState _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ReportAgentStateDefaultTypeInternal _ReportAgentState_default_instance_;

inline constexpr RegisterAgentRespond::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _agentid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR RegisterAgentRespond::RegisterAgentRespond(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct RegisterAgentRespondDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RegisterAgentRespondDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RegisterAgentRespondDefaultTypeInternal() {}
  union {
    RegisterAgentRespond _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RegisterAgentRespondDefaultTypeInternal _RegisterAgentRespond_default_instance_;

inline constexpr RegisterAgentRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _ip_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _mac_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _netdevname_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _machineid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _hostname_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR RegisterAgentRequest::RegisterAgentRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct RegisterAgentRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RegisterAgentRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RegisterAgentRequestDefaultTypeInternal() {}
  union {
    RegisterAgentRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RegisterAgentRequestDefaultTypeInternal _RegisterAgentRequest_default_instance_;

inline constexpr Pong::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _agentid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _msg_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Pong::Pong(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct PongDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PongDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PongDefaultTypeInternal() {}
  union {
    Pong _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PongDefaultTypeInternal _Pong_default_instance_;

inline constexpr Ping::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _msg_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Ping::Ping(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct PingDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PingDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PingDefaultTypeInternal() {}
  union {
    Ping _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PingDefaultTypeInternal _Ping_default_instance_;

inline constexpr AuthRespond::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _agentid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR AuthRespond::AuthRespond(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct AuthRespondDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AuthRespondDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AuthRespondDefaultTypeInternal() {}
  union {
    AuthRespond _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AuthRespondDefaultTypeInternal _AuthRespond_default_instance_;

inline constexpr AuthRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _agentid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR AuthRequest::AuthRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct AuthRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AuthRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AuthRequestDefaultTypeInternal() {}
  union {
    AuthRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AuthRequestDefaultTypeInternal _AuthRequest_default_instance_;
}  // namespace internal
}  // namespace ylg
static ::_pb::Metadata file_level_metadata_controller_2eproto[9];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_controller_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_controller_2eproto = nullptr;
const ::uint32_t TableStruct_controller_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::ylg::internal::Ping, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::ylg::internal::Ping, _impl_._msg_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::ylg::internal::Pong, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::ylg::internal::Pong, _impl_._agentid_),
    PROTOBUF_FIELD_OFFSET(::ylg::internal::Pong, _impl_._msg_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::ylg::internal::AuthRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::ylg::internal::AuthRequest, _impl_._agentid_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::ylg::internal::AuthRespond, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::ylg::internal::AuthRespond, _impl_._agentid_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::ylg::internal::RegisterAgentRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::ylg::internal::RegisterAgentRequest, _impl_._ip_),
    PROTOBUF_FIELD_OFFSET(::ylg::internal::RegisterAgentRequest, _impl_._mac_),
    PROTOBUF_FIELD_OFFSET(::ylg::internal::RegisterAgentRequest, _impl_._netdevname_),
    PROTOBUF_FIELD_OFFSET(::ylg::internal::RegisterAgentRequest, _impl_._machineid_),
    PROTOBUF_FIELD_OFFSET(::ylg::internal::RegisterAgentRequest, _impl_._hostname_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::ylg::internal::RegisterAgentRespond, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::ylg::internal::RegisterAgentRespond, _impl_._agentid_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::ylg::internal::UnregisterAgentRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::ylg::internal::UnregisterAgentRequest, _impl_._agentid_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::ylg::internal::UnregisterAgentRespond, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::ylg::internal::UnregisterAgentRespond, _impl_._agentid_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::ylg::internal::ReportAgentState, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::ylg::internal::ReportAgentState, _impl_._agentid_),
    PROTOBUF_FIELD_OFFSET(::ylg::internal::ReportAgentState, _impl_._state_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::ylg::internal::Ping)},
        {9, -1, -1, sizeof(::ylg::internal::Pong)},
        {19, -1, -1, sizeof(::ylg::internal::AuthRequest)},
        {28, -1, -1, sizeof(::ylg::internal::AuthRespond)},
        {37, -1, -1, sizeof(::ylg::internal::RegisterAgentRequest)},
        {50, -1, -1, sizeof(::ylg::internal::RegisterAgentRespond)},
        {59, -1, -1, sizeof(::ylg::internal::UnregisterAgentRequest)},
        {68, -1, -1, sizeof(::ylg::internal::UnregisterAgentRespond)},
        {77, -1, -1, sizeof(::ylg::internal::ReportAgentState)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::ylg::internal::_Ping_default_instance_._instance,
    &::ylg::internal::_Pong_default_instance_._instance,
    &::ylg::internal::_AuthRequest_default_instance_._instance,
    &::ylg::internal::_AuthRespond_default_instance_._instance,
    &::ylg::internal::_RegisterAgentRequest_default_instance_._instance,
    &::ylg::internal::_RegisterAgentRespond_default_instance_._instance,
    &::ylg::internal::_UnregisterAgentRequest_default_instance_._instance,
    &::ylg::internal::_UnregisterAgentRespond_default_instance_._instance,
    &::ylg::internal::_ReportAgentState_default_instance_._instance,
};
const char descriptor_table_protodef_controller_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\020controller.proto\022\014ylg.internal\032\nbase.p"
    "roto\"\024\n\004Ping\022\014\n\004_msg\030\001 \001(\t\"&\n\004Pong\022\020\n\010_a"
    "gentID\030\001 \001(\t\022\014\n\004_msg\030\002 \001(\t\"\037\n\013AuthReques"
    "t\022\020\n\010_agentID\030\001 \001(\t\"\037\n\013AuthRespond\022\020\n\010_a"
    "gentID\030\001 \001(\t\"m\n\024RegisterAgentRequest\022\013\n\003"
    "_ip\030\001 \001(\t\022\014\n\004_mac\030\002 \001(\t\022\023\n\013_netDevName\030\003"
    " \001(\t\022\022\n\n_machineID\030\004 \001(\t\022\021\n\t_hostName\030\005 "
    "\001(\t\"(\n\024RegisterAgentRespond\022\020\n\010_agentID\030"
    "\001 \001(\t\"*\n\026UnregisterAgentRequest\022\020\n\010_agen"
    "tID\030\001 \001(\t\"*\n\026UnregisterAgentRespond\022\020\n\010_"
    "agentID\030\001 \001(\t\"N\n\020ReportAgentState\022\020\n\010_ag"
    "entID\030\001 \001(\t\022(\n\006_state\030\002 \001(\0162\030.ylg.intern"
    "al.AgentStateb\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_controller_2eproto_deps[1] =
    {
        &::descriptor_table_base_2eproto,
};
static ::absl::once_flag descriptor_table_controller_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_controller_2eproto = {
    false,
    false,
    501,
    descriptor_table_protodef_controller_2eproto,
    "controller.proto",
    &descriptor_table_controller_2eproto_once,
    descriptor_table_controller_2eproto_deps,
    1,
    9,
    schemas,
    file_default_instances,
    TableStruct_controller_2eproto::offsets,
    file_level_metadata_controller_2eproto,
    file_level_enum_descriptors_controller_2eproto,
    file_level_service_descriptors_controller_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_controller_2eproto_getter() {
  return &descriptor_table_controller_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_controller_2eproto(&descriptor_table_controller_2eproto);
namespace ylg {
namespace internal {
// ===================================================================

class Ping::_Internal {
 public:
};

Ping::Ping(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ylg.internal.Ping)
}
inline PROTOBUF_NDEBUG_INLINE Ping::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _msg_(arena, from._msg_),
        _cached_size_{0} {}

Ping::Ping(
    ::google::protobuf::Arena* arena,
    const Ping& from)
    : ::google::protobuf::Message(arena) {
  Ping* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:ylg.internal.Ping)
}
inline PROTOBUF_NDEBUG_INLINE Ping::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _msg_(arena),
        _cached_size_{0} {}

inline void Ping::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
Ping::~Ping() {
  // @@protoc_insertion_point(destructor:ylg.internal.Ping)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Ping::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_._msg_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void Ping::Clear() {
// @@protoc_insertion_point(message_clear_start:ylg.internal.Ping)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_._msg_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* Ping::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 30, 2> Ping::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_Ping_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string _msg = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Ping, _impl_._msg_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string _msg = 1;
    {PROTOBUF_FIELD_OFFSET(Ping, _impl_._msg_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\21\4\0\0\0\0\0\0"
    "ylg.internal.Ping"
    "_msg"
  }},
};

::uint8_t* Ping::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ylg.internal.Ping)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string _msg = 1;
  if (!this->_internal__msg().empty()) {
    const std::string& _s = this->_internal__msg();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ylg.internal.Ping._msg");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ylg.internal.Ping)
  return target;
}

::size_t Ping::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ylg.internal.Ping)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string _msg = 1;
  if (!this->_internal__msg().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal__msg());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData Ping::_class_data_ = {
    Ping::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* Ping::GetClassData() const {
  return &_class_data_;
}

void Ping::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<Ping*>(&to_msg);
  auto& from = static_cast<const Ping&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ylg.internal.Ping)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal__msg().empty()) {
    _this->_internal_set__msg(from._internal__msg());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Ping::CopyFrom(const Ping& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ylg.internal.Ping)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Ping::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* Ping::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void Ping::InternalSwap(Ping* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_._msg_, &other->_impl_._msg_, arena);
}

::google::protobuf::Metadata Ping::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_controller_2eproto_getter, &descriptor_table_controller_2eproto_once,
      file_level_metadata_controller_2eproto[0]);
}
// ===================================================================

class Pong::_Internal {
 public:
};

Pong::Pong(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ylg.internal.Pong)
}
inline PROTOBUF_NDEBUG_INLINE Pong::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _agentid_(arena, from._agentid_),
        _msg_(arena, from._msg_),
        _cached_size_{0} {}

Pong::Pong(
    ::google::protobuf::Arena* arena,
    const Pong& from)
    : ::google::protobuf::Message(arena) {
  Pong* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:ylg.internal.Pong)
}
inline PROTOBUF_NDEBUG_INLINE Pong::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _agentid_(arena),
        _msg_(arena),
        _cached_size_{0} {}

inline void Pong::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
Pong::~Pong() {
  // @@protoc_insertion_point(destructor:ylg.internal.Pong)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Pong::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_._agentid_.Destroy();
  _impl_._msg_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void Pong::Clear() {
// @@protoc_insertion_point(message_clear_start:ylg.internal.Pong)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_._agentid_.ClearToEmpty();
  _impl_._msg_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* Pong::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 38, 2> Pong::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_Pong_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string _msg = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(Pong, _impl_._msg_)}},
    // string _agentID = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Pong, _impl_._agentid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string _agentID = 1;
    {PROTOBUF_FIELD_OFFSET(Pong, _impl_._agentid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string _msg = 2;
    {PROTOBUF_FIELD_OFFSET(Pong, _impl_._msg_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\21\10\4\0\0\0\0\0"
    "ylg.internal.Pong"
    "_agentID"
    "_msg"
  }},
};

::uint8_t* Pong::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ylg.internal.Pong)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string _agentID = 1;
  if (!this->_internal__agentid().empty()) {
    const std::string& _s = this->_internal__agentid();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ylg.internal.Pong._agentID");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // string _msg = 2;
  if (!this->_internal__msg().empty()) {
    const std::string& _s = this->_internal__msg();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ylg.internal.Pong._msg");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ylg.internal.Pong)
  return target;
}

::size_t Pong::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ylg.internal.Pong)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string _agentID = 1;
  if (!this->_internal__agentid().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal__agentid());
  }

  // string _msg = 2;
  if (!this->_internal__msg().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal__msg());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData Pong::_class_data_ = {
    Pong::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* Pong::GetClassData() const {
  return &_class_data_;
}

void Pong::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<Pong*>(&to_msg);
  auto& from = static_cast<const Pong&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ylg.internal.Pong)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal__agentid().empty()) {
    _this->_internal_set__agentid(from._internal__agentid());
  }
  if (!from._internal__msg().empty()) {
    _this->_internal_set__msg(from._internal__msg());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Pong::CopyFrom(const Pong& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ylg.internal.Pong)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Pong::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* Pong::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void Pong::InternalSwap(Pong* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_._agentid_, &other->_impl_._agentid_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_._msg_, &other->_impl_._msg_, arena);
}

::google::protobuf::Metadata Pong::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_controller_2eproto_getter, &descriptor_table_controller_2eproto_once,
      file_level_metadata_controller_2eproto[1]);
}
// ===================================================================

class AuthRequest::_Internal {
 public:
};

AuthRequest::AuthRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ylg.internal.AuthRequest)
}
inline PROTOBUF_NDEBUG_INLINE AuthRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _agentid_(arena, from._agentid_),
        _cached_size_{0} {}

AuthRequest::AuthRequest(
    ::google::protobuf::Arena* arena,
    const AuthRequest& from)
    : ::google::protobuf::Message(arena) {
  AuthRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:ylg.internal.AuthRequest)
}
inline PROTOBUF_NDEBUG_INLINE AuthRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _agentid_(arena),
        _cached_size_{0} {}

inline void AuthRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
AuthRequest::~AuthRequest() {
  // @@protoc_insertion_point(destructor:ylg.internal.AuthRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void AuthRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_._agentid_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void AuthRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:ylg.internal.AuthRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_._agentid_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* AuthRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 41, 2> AuthRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_AuthRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string _agentID = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(AuthRequest, _impl_._agentid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string _agentID = 1;
    {PROTOBUF_FIELD_OFFSET(AuthRequest, _impl_._agentid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\30\10\0\0\0\0\0\0"
    "ylg.internal.AuthRequest"
    "_agentID"
  }},
};

::uint8_t* AuthRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ylg.internal.AuthRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string _agentID = 1;
  if (!this->_internal__agentid().empty()) {
    const std::string& _s = this->_internal__agentid();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ylg.internal.AuthRequest._agentID");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ylg.internal.AuthRequest)
  return target;
}

::size_t AuthRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ylg.internal.AuthRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string _agentID = 1;
  if (!this->_internal__agentid().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal__agentid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData AuthRequest::_class_data_ = {
    AuthRequest::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* AuthRequest::GetClassData() const {
  return &_class_data_;
}

void AuthRequest::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<AuthRequest*>(&to_msg);
  auto& from = static_cast<const AuthRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ylg.internal.AuthRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal__agentid().empty()) {
    _this->_internal_set__agentid(from._internal__agentid());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void AuthRequest::CopyFrom(const AuthRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ylg.internal.AuthRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool AuthRequest::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* AuthRequest::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void AuthRequest::InternalSwap(AuthRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_._agentid_, &other->_impl_._agentid_, arena);
}

::google::protobuf::Metadata AuthRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_controller_2eproto_getter, &descriptor_table_controller_2eproto_once,
      file_level_metadata_controller_2eproto[2]);
}
// ===================================================================

class AuthRespond::_Internal {
 public:
};

AuthRespond::AuthRespond(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ylg.internal.AuthRespond)
}
inline PROTOBUF_NDEBUG_INLINE AuthRespond::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _agentid_(arena, from._agentid_),
        _cached_size_{0} {}

AuthRespond::AuthRespond(
    ::google::protobuf::Arena* arena,
    const AuthRespond& from)
    : ::google::protobuf::Message(arena) {
  AuthRespond* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:ylg.internal.AuthRespond)
}
inline PROTOBUF_NDEBUG_INLINE AuthRespond::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _agentid_(arena),
        _cached_size_{0} {}

inline void AuthRespond::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
AuthRespond::~AuthRespond() {
  // @@protoc_insertion_point(destructor:ylg.internal.AuthRespond)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void AuthRespond::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_._agentid_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void AuthRespond::Clear() {
// @@protoc_insertion_point(message_clear_start:ylg.internal.AuthRespond)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_._agentid_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* AuthRespond::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 41, 2> AuthRespond::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_AuthRespond_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string _agentID = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(AuthRespond, _impl_._agentid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string _agentID = 1;
    {PROTOBUF_FIELD_OFFSET(AuthRespond, _impl_._agentid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\30\10\0\0\0\0\0\0"
    "ylg.internal.AuthRespond"
    "_agentID"
  }},
};

::uint8_t* AuthRespond::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ylg.internal.AuthRespond)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string _agentID = 1;
  if (!this->_internal__agentid().empty()) {
    const std::string& _s = this->_internal__agentid();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ylg.internal.AuthRespond._agentID");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ylg.internal.AuthRespond)
  return target;
}

::size_t AuthRespond::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ylg.internal.AuthRespond)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string _agentID = 1;
  if (!this->_internal__agentid().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal__agentid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData AuthRespond::_class_data_ = {
    AuthRespond::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* AuthRespond::GetClassData() const {
  return &_class_data_;
}

void AuthRespond::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<AuthRespond*>(&to_msg);
  auto& from = static_cast<const AuthRespond&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ylg.internal.AuthRespond)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal__agentid().empty()) {
    _this->_internal_set__agentid(from._internal__agentid());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void AuthRespond::CopyFrom(const AuthRespond& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ylg.internal.AuthRespond)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool AuthRespond::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* AuthRespond::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void AuthRespond::InternalSwap(AuthRespond* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_._agentid_, &other->_impl_._agentid_, arena);
}

::google::protobuf::Metadata AuthRespond::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_controller_2eproto_getter, &descriptor_table_controller_2eproto_once,
      file_level_metadata_controller_2eproto[3]);
}
// ===================================================================

class RegisterAgentRequest::_Internal {
 public:
};

RegisterAgentRequest::RegisterAgentRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ylg.internal.RegisterAgentRequest)
}
inline PROTOBUF_NDEBUG_INLINE RegisterAgentRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _ip_(arena, from._ip_),
        _mac_(arena, from._mac_),
        _netdevname_(arena, from._netdevname_),
        _machineid_(arena, from._machineid_),
        _hostname_(arena, from._hostname_),
        _cached_size_{0} {}

RegisterAgentRequest::RegisterAgentRequest(
    ::google::protobuf::Arena* arena,
    const RegisterAgentRequest& from)
    : ::google::protobuf::Message(arena) {
  RegisterAgentRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:ylg.internal.RegisterAgentRequest)
}
inline PROTOBUF_NDEBUG_INLINE RegisterAgentRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _ip_(arena),
        _mac_(arena),
        _netdevname_(arena),
        _machineid_(arena),
        _hostname_(arena),
        _cached_size_{0} {}

inline void RegisterAgentRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
RegisterAgentRequest::~RegisterAgentRequest() {
  // @@protoc_insertion_point(destructor:ylg.internal.RegisterAgentRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void RegisterAgentRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_._ip_.Destroy();
  _impl_._mac_.Destroy();
  _impl_._netdevname_.Destroy();
  _impl_._machineid_.Destroy();
  _impl_._hostname_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void RegisterAgentRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:ylg.internal.RegisterAgentRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_._ip_.ClearToEmpty();
  _impl_._mac_.ClearToEmpty();
  _impl_._netdevname_.ClearToEmpty();
  _impl_._machineid_.ClearToEmpty();
  _impl_._hostname_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* RegisterAgentRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 0, 79, 2> RegisterAgentRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_RegisterAgentRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string _ip = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(RegisterAgentRequest, _impl_._ip_)}},
    // string _mac = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(RegisterAgentRequest, _impl_._mac_)}},
    // string _netDevName = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(RegisterAgentRequest, _impl_._netdevname_)}},
    // string _machineID = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(RegisterAgentRequest, _impl_._machineid_)}},
    // string _hostName = 5;
    {::_pbi::TcParser::FastUS1,
     {42, 63, 0, PROTOBUF_FIELD_OFFSET(RegisterAgentRequest, _impl_._hostname_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // string _ip = 1;
    {PROTOBUF_FIELD_OFFSET(RegisterAgentRequest, _impl_._ip_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string _mac = 2;
    {PROTOBUF_FIELD_OFFSET(RegisterAgentRequest, _impl_._mac_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string _netDevName = 3;
    {PROTOBUF_FIELD_OFFSET(RegisterAgentRequest, _impl_._netdevname_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string _machineID = 4;
    {PROTOBUF_FIELD_OFFSET(RegisterAgentRequest, _impl_._machineid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string _hostName = 5;
    {PROTOBUF_FIELD_OFFSET(RegisterAgentRequest, _impl_._hostname_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\41\3\4\13\12\11\0\0"
    "ylg.internal.RegisterAgentRequest"
    "_ip"
    "_mac"
    "_netDevName"
    "_machineID"
    "_hostName"
  }},
};

::uint8_t* RegisterAgentRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ylg.internal.RegisterAgentRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string _ip = 1;
  if (!this->_internal__ip().empty()) {
    const std::string& _s = this->_internal__ip();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ylg.internal.RegisterAgentRequest._ip");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // string _mac = 2;
  if (!this->_internal__mac().empty()) {
    const std::string& _s = this->_internal__mac();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ylg.internal.RegisterAgentRequest._mac");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // string _netDevName = 3;
  if (!this->_internal__netdevname().empty()) {
    const std::string& _s = this->_internal__netdevname();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ylg.internal.RegisterAgentRequest._netDevName");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  // string _machineID = 4;
  if (!this->_internal__machineid().empty()) {
    const std::string& _s = this->_internal__machineid();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ylg.internal.RegisterAgentRequest._machineID");
    target = stream->WriteStringMaybeAliased(4, _s, target);
  }

  // string _hostName = 5;
  if (!this->_internal__hostname().empty()) {
    const std::string& _s = this->_internal__hostname();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ylg.internal.RegisterAgentRequest._hostName");
    target = stream->WriteStringMaybeAliased(5, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ylg.internal.RegisterAgentRequest)
  return target;
}

::size_t RegisterAgentRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ylg.internal.RegisterAgentRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string _ip = 1;
  if (!this->_internal__ip().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal__ip());
  }

  // string _mac = 2;
  if (!this->_internal__mac().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal__mac());
  }

  // string _netDevName = 3;
  if (!this->_internal__netdevname().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal__netdevname());
  }

  // string _machineID = 4;
  if (!this->_internal__machineid().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal__machineid());
  }

  // string _hostName = 5;
  if (!this->_internal__hostname().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal__hostname());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData RegisterAgentRequest::_class_data_ = {
    RegisterAgentRequest::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* RegisterAgentRequest::GetClassData() const {
  return &_class_data_;
}

void RegisterAgentRequest::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<RegisterAgentRequest*>(&to_msg);
  auto& from = static_cast<const RegisterAgentRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ylg.internal.RegisterAgentRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal__ip().empty()) {
    _this->_internal_set__ip(from._internal__ip());
  }
  if (!from._internal__mac().empty()) {
    _this->_internal_set__mac(from._internal__mac());
  }
  if (!from._internal__netdevname().empty()) {
    _this->_internal_set__netdevname(from._internal__netdevname());
  }
  if (!from._internal__machineid().empty()) {
    _this->_internal_set__machineid(from._internal__machineid());
  }
  if (!from._internal__hostname().empty()) {
    _this->_internal_set__hostname(from._internal__hostname());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RegisterAgentRequest::CopyFrom(const RegisterAgentRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ylg.internal.RegisterAgentRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool RegisterAgentRequest::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* RegisterAgentRequest::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void RegisterAgentRequest::InternalSwap(RegisterAgentRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_._ip_, &other->_impl_._ip_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_._mac_, &other->_impl_._mac_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_._netdevname_, &other->_impl_._netdevname_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_._machineid_, &other->_impl_._machineid_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_._hostname_, &other->_impl_._hostname_, arena);
}

::google::protobuf::Metadata RegisterAgentRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_controller_2eproto_getter, &descriptor_table_controller_2eproto_once,
      file_level_metadata_controller_2eproto[4]);
}
// ===================================================================

class RegisterAgentRespond::_Internal {
 public:
};

RegisterAgentRespond::RegisterAgentRespond(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ylg.internal.RegisterAgentRespond)
}
inline PROTOBUF_NDEBUG_INLINE RegisterAgentRespond::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _agentid_(arena, from._agentid_),
        _cached_size_{0} {}

RegisterAgentRespond::RegisterAgentRespond(
    ::google::protobuf::Arena* arena,
    const RegisterAgentRespond& from)
    : ::google::protobuf::Message(arena) {
  RegisterAgentRespond* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:ylg.internal.RegisterAgentRespond)
}
inline PROTOBUF_NDEBUG_INLINE RegisterAgentRespond::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _agentid_(arena),
        _cached_size_{0} {}

inline void RegisterAgentRespond::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
RegisterAgentRespond::~RegisterAgentRespond() {
  // @@protoc_insertion_point(destructor:ylg.internal.RegisterAgentRespond)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void RegisterAgentRespond::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_._agentid_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void RegisterAgentRespond::Clear() {
// @@protoc_insertion_point(message_clear_start:ylg.internal.RegisterAgentRespond)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_._agentid_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* RegisterAgentRespond::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 50, 2> RegisterAgentRespond::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_RegisterAgentRespond_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string _agentID = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(RegisterAgentRespond, _impl_._agentid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string _agentID = 1;
    {PROTOBUF_FIELD_OFFSET(RegisterAgentRespond, _impl_._agentid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\41\10\0\0\0\0\0\0"
    "ylg.internal.RegisterAgentRespond"
    "_agentID"
  }},
};

::uint8_t* RegisterAgentRespond::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ylg.internal.RegisterAgentRespond)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string _agentID = 1;
  if (!this->_internal__agentid().empty()) {
    const std::string& _s = this->_internal__agentid();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ylg.internal.RegisterAgentRespond._agentID");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ylg.internal.RegisterAgentRespond)
  return target;
}

::size_t RegisterAgentRespond::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ylg.internal.RegisterAgentRespond)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string _agentID = 1;
  if (!this->_internal__agentid().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal__agentid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData RegisterAgentRespond::_class_data_ = {
    RegisterAgentRespond::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* RegisterAgentRespond::GetClassData() const {
  return &_class_data_;
}

void RegisterAgentRespond::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<RegisterAgentRespond*>(&to_msg);
  auto& from = static_cast<const RegisterAgentRespond&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ylg.internal.RegisterAgentRespond)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal__agentid().empty()) {
    _this->_internal_set__agentid(from._internal__agentid());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RegisterAgentRespond::CopyFrom(const RegisterAgentRespond& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ylg.internal.RegisterAgentRespond)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool RegisterAgentRespond::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* RegisterAgentRespond::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void RegisterAgentRespond::InternalSwap(RegisterAgentRespond* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_._agentid_, &other->_impl_._agentid_, arena);
}

::google::protobuf::Metadata RegisterAgentRespond::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_controller_2eproto_getter, &descriptor_table_controller_2eproto_once,
      file_level_metadata_controller_2eproto[5]);
}
// ===================================================================

class UnregisterAgentRequest::_Internal {
 public:
};

UnregisterAgentRequest::UnregisterAgentRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ylg.internal.UnregisterAgentRequest)
}
inline PROTOBUF_NDEBUG_INLINE UnregisterAgentRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _agentid_(arena, from._agentid_),
        _cached_size_{0} {}

UnregisterAgentRequest::UnregisterAgentRequest(
    ::google::protobuf::Arena* arena,
    const UnregisterAgentRequest& from)
    : ::google::protobuf::Message(arena) {
  UnregisterAgentRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:ylg.internal.UnregisterAgentRequest)
}
inline PROTOBUF_NDEBUG_INLINE UnregisterAgentRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _agentid_(arena),
        _cached_size_{0} {}

inline void UnregisterAgentRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
UnregisterAgentRequest::~UnregisterAgentRequest() {
  // @@protoc_insertion_point(destructor:ylg.internal.UnregisterAgentRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void UnregisterAgentRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_._agentid_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void UnregisterAgentRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:ylg.internal.UnregisterAgentRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_._agentid_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* UnregisterAgentRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 52, 2> UnregisterAgentRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_UnregisterAgentRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string _agentID = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(UnregisterAgentRequest, _impl_._agentid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string _agentID = 1;
    {PROTOBUF_FIELD_OFFSET(UnregisterAgentRequest, _impl_._agentid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\43\10\0\0\0\0\0\0"
    "ylg.internal.UnregisterAgentRequest"
    "_agentID"
  }},
};

::uint8_t* UnregisterAgentRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ylg.internal.UnregisterAgentRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string _agentID = 1;
  if (!this->_internal__agentid().empty()) {
    const std::string& _s = this->_internal__agentid();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ylg.internal.UnregisterAgentRequest._agentID");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ylg.internal.UnregisterAgentRequest)
  return target;
}

::size_t UnregisterAgentRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ylg.internal.UnregisterAgentRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string _agentID = 1;
  if (!this->_internal__agentid().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal__agentid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData UnregisterAgentRequest::_class_data_ = {
    UnregisterAgentRequest::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* UnregisterAgentRequest::GetClassData() const {
  return &_class_data_;
}

void UnregisterAgentRequest::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<UnregisterAgentRequest*>(&to_msg);
  auto& from = static_cast<const UnregisterAgentRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ylg.internal.UnregisterAgentRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal__agentid().empty()) {
    _this->_internal_set__agentid(from._internal__agentid());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void UnregisterAgentRequest::CopyFrom(const UnregisterAgentRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ylg.internal.UnregisterAgentRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool UnregisterAgentRequest::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* UnregisterAgentRequest::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void UnregisterAgentRequest::InternalSwap(UnregisterAgentRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_._agentid_, &other->_impl_._agentid_, arena);
}

::google::protobuf::Metadata UnregisterAgentRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_controller_2eproto_getter, &descriptor_table_controller_2eproto_once,
      file_level_metadata_controller_2eproto[6]);
}
// ===================================================================

class UnregisterAgentRespond::_Internal {
 public:
};

UnregisterAgentRespond::UnregisterAgentRespond(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ylg.internal.UnregisterAgentRespond)
}
inline PROTOBUF_NDEBUG_INLINE UnregisterAgentRespond::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _agentid_(arena, from._agentid_),
        _cached_size_{0} {}

UnregisterAgentRespond::UnregisterAgentRespond(
    ::google::protobuf::Arena* arena,
    const UnregisterAgentRespond& from)
    : ::google::protobuf::Message(arena) {
  UnregisterAgentRespond* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:ylg.internal.UnregisterAgentRespond)
}
inline PROTOBUF_NDEBUG_INLINE UnregisterAgentRespond::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _agentid_(arena),
        _cached_size_{0} {}

inline void UnregisterAgentRespond::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
UnregisterAgentRespond::~UnregisterAgentRespond() {
  // @@protoc_insertion_point(destructor:ylg.internal.UnregisterAgentRespond)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void UnregisterAgentRespond::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_._agentid_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void UnregisterAgentRespond::Clear() {
// @@protoc_insertion_point(message_clear_start:ylg.internal.UnregisterAgentRespond)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_._agentid_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* UnregisterAgentRespond::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 52, 2> UnregisterAgentRespond::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_UnregisterAgentRespond_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string _agentID = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(UnregisterAgentRespond, _impl_._agentid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string _agentID = 1;
    {PROTOBUF_FIELD_OFFSET(UnregisterAgentRespond, _impl_._agentid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\43\10\0\0\0\0\0\0"
    "ylg.internal.UnregisterAgentRespond"
    "_agentID"
  }},
};

::uint8_t* UnregisterAgentRespond::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ylg.internal.UnregisterAgentRespond)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string _agentID = 1;
  if (!this->_internal__agentid().empty()) {
    const std::string& _s = this->_internal__agentid();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ylg.internal.UnregisterAgentRespond._agentID");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ylg.internal.UnregisterAgentRespond)
  return target;
}

::size_t UnregisterAgentRespond::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ylg.internal.UnregisterAgentRespond)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string _agentID = 1;
  if (!this->_internal__agentid().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal__agentid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData UnregisterAgentRespond::_class_data_ = {
    UnregisterAgentRespond::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* UnregisterAgentRespond::GetClassData() const {
  return &_class_data_;
}

void UnregisterAgentRespond::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<UnregisterAgentRespond*>(&to_msg);
  auto& from = static_cast<const UnregisterAgentRespond&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ylg.internal.UnregisterAgentRespond)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal__agentid().empty()) {
    _this->_internal_set__agentid(from._internal__agentid());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void UnregisterAgentRespond::CopyFrom(const UnregisterAgentRespond& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ylg.internal.UnregisterAgentRespond)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool UnregisterAgentRespond::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* UnregisterAgentRespond::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void UnregisterAgentRespond::InternalSwap(UnregisterAgentRespond* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_._agentid_, &other->_impl_._agentid_, arena);
}

::google::protobuf::Metadata UnregisterAgentRespond::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_controller_2eproto_getter, &descriptor_table_controller_2eproto_once,
      file_level_metadata_controller_2eproto[7]);
}
// ===================================================================

class ReportAgentState::_Internal {
 public:
};

ReportAgentState::ReportAgentState(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ylg.internal.ReportAgentState)
}
inline PROTOBUF_NDEBUG_INLINE ReportAgentState::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _agentid_(arena, from._agentid_),
        _cached_size_{0} {}

ReportAgentState::ReportAgentState(
    ::google::protobuf::Arena* arena,
    const ReportAgentState& from)
    : ::google::protobuf::Message(arena) {
  ReportAgentState* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_._state_ = from._impl_._state_;

  // @@protoc_insertion_point(copy_constructor:ylg.internal.ReportAgentState)
}
inline PROTOBUF_NDEBUG_INLINE ReportAgentState::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _agentid_(arena),
        _cached_size_{0} {}

inline void ReportAgentState::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_._state_ = {};
}
ReportAgentState::~ReportAgentState() {
  // @@protoc_insertion_point(destructor:ylg.internal.ReportAgentState)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ReportAgentState::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_._agentid_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void ReportAgentState::Clear() {
// @@protoc_insertion_point(message_clear_start:ylg.internal.ReportAgentState)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_._agentid_.ClearToEmpty();
  _impl_._state_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* ReportAgentState::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 46, 2> ReportAgentState::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_ReportAgentState_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // .ylg.internal.AgentState _state = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ReportAgentState, _impl_._state_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(ReportAgentState, _impl_._state_)}},
    // string _agentID = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ReportAgentState, _impl_._agentid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string _agentID = 1;
    {PROTOBUF_FIELD_OFFSET(ReportAgentState, _impl_._agentid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .ylg.internal.AgentState _state = 2;
    {PROTOBUF_FIELD_OFFSET(ReportAgentState, _impl_._state_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
  }},
  // no aux_entries
  {{
    "\35\10\0\0\0\0\0\0"
    "ylg.internal.ReportAgentState"
    "_agentID"
  }},
};

::uint8_t* ReportAgentState::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ylg.internal.ReportAgentState)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string _agentID = 1;
  if (!this->_internal__agentid().empty()) {
    const std::string& _s = this->_internal__agentid();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ylg.internal.ReportAgentState._agentID");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // .ylg.internal.AgentState _state = 2;
  if (this->_internal__state() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        2, this->_internal__state(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ylg.internal.ReportAgentState)
  return target;
}

::size_t ReportAgentState::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ylg.internal.ReportAgentState)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string _agentID = 1;
  if (!this->_internal__agentid().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal__agentid());
  }

  // .ylg.internal.AgentState _state = 2;
  if (this->_internal__state() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal__state());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData ReportAgentState::_class_data_ = {
    ReportAgentState::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* ReportAgentState::GetClassData() const {
  return &_class_data_;
}

void ReportAgentState::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<ReportAgentState*>(&to_msg);
  auto& from = static_cast<const ReportAgentState&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ylg.internal.ReportAgentState)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal__agentid().empty()) {
    _this->_internal_set__agentid(from._internal__agentid());
  }
  if (from._internal__state() != 0) {
    _this->_internal_set__state(from._internal__state());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ReportAgentState::CopyFrom(const ReportAgentState& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ylg.internal.ReportAgentState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ReportAgentState::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* ReportAgentState::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void ReportAgentState::InternalSwap(ReportAgentState* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_._agentid_, &other->_impl_._agentid_, arena);
  swap(_impl_._state_, other->_impl_._state_);
}

::google::protobuf::Metadata ReportAgentState::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_controller_2eproto_getter, &descriptor_table_controller_2eproto_once,
      file_level_metadata_controller_2eproto[8]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace internal
}  // namespace ylg
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
